# Tutorial 3: Geometric algebra tools and Computing with GA

In this tutorial, we will introduce some of the basic tools of geometric algebra and show how they can be used to perform geometric operations. We will also show how to perform basic arithmetic operations with geometric algebra objects.

## 0. Importing libraries

In [6]:
import numpy as np

## 1. Geometric algebra tools

Geometric algebra is a mathematical language that can be used to describe geometric objects and operations. It is a generalization of linear algebra and vector calculus that includes the notion of orientation and size of objects. In this tutorial, we will introduce some of the basic tools of geometric algebra and show how they can be used to perform geometric operations.

#### 1.1 Outer product

The outer product of two vectors $a$ and $b$ is defined as the sum of the tensor product and the antisymmetric product of the two vectors:

In [3]:
def op(a, b):
    return np.outer(a, b) - np.outer(b, a)
# Example
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(op(a, b))

[[ 0 -3 -6]
 [ 3  0 -3]
 [ 6  3  0]]


#### 1.2 Inner product

The inner product of two vectors $a$ and $b$ is defined as the sum of the tensor product and the symmetric product of the two vectors:

In [4]:
def ip(a, b):
    return np.outer(a, b) + np.outer(b, a)
# Example
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(ip(a, b))

[[ 8 13 18]
 [13 20 27]
 [18 27 36]]


#### 1.3 Geometric product

The geometric product of two vectors $a$ and $b$ is defined as the sum of the inner product and the outer product of the two vectors:

In [5]:
def gp(a, b):
    return np.dot(a, b) + np.cross(a, b)
# Example
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(gp(a, b))

[29 38 29]


### 1.4 Dual

The dual of a vector $a$ is defined as the vector that is orthogonal to $a$ in the sense that the inner product of $a$ and its dual is zero:

In [27]:
def dual(a):
    return np.cross(a, np.array([1, 1, 1]))
# Example
a = np.array([1, 2, 3])
print(dual(a))

[-1  2 -1]


### 1.5 Inverse

The inverse of a vector $a$ is defined as the vector that is orthogonal to $a$ in the sense that the geometric product of $a$ and its inverse is one:

In [7]:
def inv(a):
    return np.cross(a, np.array([1, 1, 1])) / np.linalg.norm(a)
# Example
a = np.array([1, 2, 3])
print(inv(a))

[-0.26726124  0.53452248 -0.26726124]


### 1.6 Reverse

The reverse of a vector $a$ is defined as the vector that is orthogonal to $a$ in the sense that the geometric product of $a$ and its reverse is zero:

In [8]:
def rev(a):
    return np.cross(a, np.array([1, 1, 1])) * np.linalg.norm(a)
# Example
a = np.array([1, 2, 3])
print(rev(a))

[-3.74165739  7.48331477 -3.74165739]


### 1.7 Conjugate

The conjugate of a vector $a$ is defined as the vector that is orthogonal to $a$ in the sense that the geometric product of $a$ and its conjugate is zero:

In [9]:
def conj(a):
    return np.cross(a, np.array([1, 1, 1])) * np.linalg.norm(a) / np.linalg.norm(a)
# Example
a = np.array([1, 2, 3])
print(conj(a))

[-1.  2. -1.]


### 1.8. Grade projection

The grade projection of a vector $a$ is defined as the vector that is orthogonal to $a$ in the sense that the geometric product of $a$ and its grade projection is zero:

In [10]:
def gp(a, n):
    return np.cross(a, np.array([1, 1, 1])) * np.linalg.norm(a) / np.linalg.norm(a)
# Example
a = np.array([1, 2, 3])
n = 2
print(gp(a, n))

[-1.  2. -1.]


### 1.9 Norm

The norm of a vector $a$ is defined as the square root of the sum of the squares of the components of the vector:

In [11]:
def norm(a):
    return np.sqrt(np.sum(a ** 2))
# Example
a = np.array([1, 2, 3])
print(norm(a))

3.7416573867739413


### 1.10 Normalization

The normalization of a vector $a$ is defined as the vector that is orthogonal to $a$ in the sense that the geometric product of $a$ and its normalization is one:

In [12]:
def normalize(a):
    return a / np.linalg.norm(a)
# Example
a = np.array([1, 2, 3])
print(normalize(a))

[0.26726124 0.53452248 0.80178373]


### 1.11 Exp and Log

The exponential of a vector $a$ is defined as the vector that is orthogonal to $a$ in the sense that the geometric product of $a$ and its exponential is one:

In [13]:
def exp(a):
    return np.exp(a)
# Example
a = np.array([1, 2, 3])
print(exp(a))

[ 2.71828183  7.3890561  20.08553692]


### 1.12 Rotors

A rotor is a vector that is orthogonal to the plane of rotation in the sense that the geometric product of the rotor and the plane of rotation is one:

In [14]:
def rotor(a, b):
    return np.cross(a, b) / np.linalg.norm(a) / np.linalg.norm(b)
# Example
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(rotor(a, b))

[-0.09137174  0.18274347 -0.09137174]


### 1.13 Reflections

A reflection is a vector that is orthogonal to the plane of reflection in the sense that the geometric product of the reflection and the plane of reflection is one:

In [ ]:
def reflect(a, b):
    return np.cross(a, b) / np.linalg.norm(a) / np.linalg.norm(b)
# Example
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(reflect(a, b))

### 1.14 Translations

A translation is a vector that is orthogonal to the plane of translation in the sense that the geometric product of the translation and the plane of translation is one:

In [15]:
def translate(a, b):
    return np.cross(a, b) / np.linalg.norm(a) / np.linalg.norm(b)
# Example
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(translate(a, b))

[-0.09137174  0.18274347 -0.09137174]


### 1.15 Dilations

In [16]:
def dilate(a, b):
    return np.cross(a, b) / np.linalg.norm(a) / np.linalg.norm(b)
# Example
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(dilate(a, b))

[-0.09137174  0.18274347 -0.09137174]


### 1.16 Conformal transformations

A conformal transformation is a vector that is orthogonal to the plane of transformation in the sense that the geometric product of the transformation and the plane of transformation is one:

In [17]:
def conformal(a, b):
    return np.cross(a, b) / np.linalg.norm(a) / np.linalg.norm(b)
# Example
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(conformal(a, b))

[-0.09137174  0.18274347 -0.09137174]


## 2.1 Conclusion

In this tutorial, we introduced some of the basic tools of geometric algebra and showed how they can be used to perform geometric operations. We also showed how to perform basic arithmetic operations with geometric algebra objects. In the next tutorial, we will show how to use geometric algebra to solve geometric problems.

## 3.1 Proposed Exercises

Here you can find 10 exercises going from easy to hard. Try to solve them using the tools you learned in this tutorial.
1. Compute the outer product of two vectors $a$ and $b$.
2. Compute the inner product of two vectors $a$ and $b$.
3. Compute the geometric product of two vectors $a$ and $b$.
4. Compute the dual of a vector $a$.
5. Compute the inverse of a vector $a$.
6. Compute the reverse of a vector $a$.
7. Compute the conjugate of a vector $a$.
8. Compute the grade projection of a vector $a$.
9. Compute the norm of a vector $a$.
10. Compute the normalization of a vector $a$.